"""Trading models used by backtest and paper-trading simulations."""

from __future__ import annotations

from datetime import date, datetime

from pydantic import BaseModel, Field


class StrategyRun(BaseModel):
    """Persisted strategy output and explanation for one run."""

    run_id: str
    strategy_id: str
    trading_date: date
    targets: dict[str, float]
    explanation: dict[str, str | float]
    created_at: datetime


class SimOrder(BaseModel):
    """Order generated by the Python simulator."""

    order_id: str
    symbol: str
    side: str = Field(pattern=r"^(BUY|SELL)$")
    quantity: int = Field(gt=0)
    price: float = Field(gt=0)
    trading_date: date
    status: str


class SimFill(BaseModel):
    """Fill produced by the deterministic daily-bar matcher."""

    fill_id: str
    order_id: str
    symbol: str
    side: str = Field(pattern=r"^(BUY|SELL)$")
    quantity: int = Field(gt=0)
    price: float = Field(gt=0)
    trading_date: date
    commission: float = Field(ge=0)
    tax: float = Field(ge=0)


class PositionSnapshot(BaseModel):
    """End-of-day position snapshot."""

    symbol: str
    quantity: int = Field(ge=0)
    market_value: float = Field(ge=0)
    cost_basis: float = Field(ge=0)


class EquityPoint(BaseModel):
    """Daily account equity point used by charts and metrics."""

    trading_date: date
    equity: float
    cash: float
    drawdown_pct: float


class BacktestMetrics(BaseModel):
    """Headline metrics for a backtest run."""

    total_return_pct: float
    max_drawdown_pct: float
    annual_turnover_pct: float
    trade_count: int


class BacktestRun(BaseModel):
    """Complete result returned by the backtest engine."""

    run_id: str
    strategy_id: str
    strategy_version: str
    data_version: str
    engine_type: str
    benchmark: str | None = None
    start_date: date
    end_date: date
    initial_cash: float
    metrics: BacktestMetrics
    equity_curve: list[EquityPoint]
    orders: list[SimOrder]
    fills: list[SimFill]
    positions: list[PositionSnapshot]
    created_at: datetime


class PaperAccount(BaseModel):
    """Current paper-trading account state."""

    account_id: str
    cash: float
    equity: float
    positions: list[PositionSnapshot]
    orders: list[SimOrder]
    fills: list[SimFill]
    equity_curve: list[EquityPoint]
    updated_at: datetime
